### ISSUE TITLE
MSRV for v6 is Rust 1.59

### ISSUE THREAD

**Issue by alpha-tango-kilo** [Nukesor/comfy-table#72]
First of all, please read the [FAQ](https://github.com/Nukesor/comfy-table/blob/main/FAQ.md) if you're having styling issues!

Otherwise feel free to go ahead :)

#### Describe the bug

The `Cargo.toml` for this library states that the MSRV is 1.58, but it can't currently compile on 1.58

#### Expected behavior

Cloning the repo and building it should work on 1.58 or the MSRV should be declared as 1.59

#### Code

N/A

#### Steps to reproduce the bug

```
> git checkout v6.0.0-rc.1
> rustup install 1.58 # if not already installed
> cargo +1.58 build
```

Error:

```
error[E0658]: destructuring assignments are unstable
  --> src\utils\arrangement\dynamic.rs:62:46
   |
62 |         (remaining_width, remaining_columns) = enforce_lower_boundary_constraints(
   |         ------------------------------------ ^
   |         |
   |         cannot assign to this expression
   |
   = note: see issue #71126 <https://github.com/rust-lang/rust/issues/71126> for more information

error[E0658]: destructuring assignments are unstable
  --> src\utils\arrangement\dynamic.rs:85:46
   |
85 |         (remaining_width, remaining_columns) = optimize_space_after_split(
   |         ------------------------------------ ^
   |         |
   |         cannot assign to this expression
   |
   = note: see issue #71126 <https://github.com/rust-lang/rust/issues/71126> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `comfy-table` due to 2 previous errors
```

#### Additional context

- Operating System: Windows 10
- comfy-table version: v6.0.0-rc.1

**Comment by Nukesor** [comment]
Thanks for the report :)

The MSRV is now also covered by the CI. Any future breakages will be noticed.

**Comment by alpha-tango-kilo** [comment]
Nice one, cheers!
